Avoid casting int to float unnecessarily
HEPData/hepdata_lib pull request #156
Opened 2021-03-17 13:47 UTC by AndreasAlbert

Our current input handling converts Variable inputs to float if they are integers. This is not needed and is detrimental when one wants to converse the discreteness of the input, e.g. for data counts. In this PR, I clean up the handling of the input values and avoid the unneeded cast.

2021-03-25 17:53 UTC, AndreasAlbert commented
Let's solve #158 as well here while we are at it

2021-03-26 10:18 UTC, clelange requested changes
Thanks for this! It's a bit unfortunate that our tests all fail at the moment. Did you happen to run them locally?

2021-03-26 10:18 UTC, clelange commented on hepdata_lib/__init__.py
> +                parsed_values = [helpers.sanitize_value(x) for x in  value_list]
Remove additional space after `in`

2021-03-26 10:18 UTC, clelange commented on hepdata_lib/helpers.py
> +    return float(value)
Add new line add end of file

2021-03-26 10:18 UTC, clelange commented on hepdata_lib/__init__.py
>              except (TypeError, ValueError):
Not sure it makes sense, but should we then raise the error in the helper as well (i.e. move the try/catch part over)?

2021-04-19 16:56 UTC, AndreasAlbert commented on hepdata_lib/__init__.py
> +                parsed_values = [helpers.sanitize_value(x) for x in  value_list]
done

2021-04-19 16:56 UTC, AndreasAlbert commented on hepdata_lib/helpers.py
> +    return float(value)
done

2021-04-19 16:57 UTC, AndreasAlbert commented on hepdata_lib/__init__.py
>              except (TypeError, ValueError):
If the exception happens within the helper, it will be on a call to `float(x)`, and the resulting error message will be very clear. I think this is fine the way it is.

2021-04-19 16:57 UTC, AndreasAlbert commented
Closes #158

2021-04-19 16:58 UTC, AndreasAlbert commented
Confirm that tests run locally (still have to fix CI)

2021-04-20 10:02 UTC, clelange commented
Also this one would have to be rebased and conflicts to be resolved...

2021-04-20 10:22 UTC, AndreasAlbert commented
Not sure why coveralls rates this as a failure. It seems all individual files either have unchanged or improved coverage, but the overall coverage reduced by some tiny amount. Rounding error?

![image](https://user-images.githubusercontent.com/9568102/115380560-fa54d600-a1d2-11eb-9901-4d65169cf8da.png)

2021-04-20 10:35 UTC, AndreasAlbert commented
I changed the settings on coveralls.io so that it will only fail for coverage decreases of 2% or more in the future. For this PR, suggest to ignore and merge @clelange

2021-04-20 14:05 UTC, clelange approved these changes
Awesome, thanks! I agree that we should ignore coverage here 😄

2021-04-20 14:06 UTC, merged