Do not write errors if all errors are zero for bin
HEPData/hepdata_lib pull request #161
Opened 2021-04-19 17:24 UTC by AndreasAlbert

Closes #159 

@GraemeWatt Is this what you imagined?

2021-04-20 10:01 UTC, clelange commented
Can you please rebase onto master to have working tests again?

2021-04-20 11:43 UTC, GraemeWatt requested changes
Many thanks for addressing the issue #159 so quickly!  I've tested the new code and it works well, but I've made a couple of suggestions for improvements before merging.

2021-04-20 11:43 UTC, GraemeWatt commented on hepdata_lib/helpers.py
> +            nonzero = nonzero | np.any((np.array(unc.values) > 0),axis=1)
Here, I'd replace `> 0` with `!= 0` in lines 259 and 161 to allow for possible uncertainties with a flipped sign (see first paragraph of the [Uncertainties](https://hepdata-submission.readthedocs.io/en/latest/data_yaml.html#uncertainties) section in the submission docs).

2021-04-20 11:43 UTC, GraemeWatt commented on hepdata_lib/__init__.py
> +            # if at least one of the uncertanities is not zero.
Typo: "uncertanities" → "uncertainties".

2021-04-20 11:43 UTC, GraemeWatt commented on hepdata_lib/__init__.py
> +                        })
The omission of the `errors` key should not be done silently, but a warning message should be printed out.  Otherwise, users will encode bins with zero uncertainties (although `errors` will now be suppressed), which will still result in a YODA export with zero uncertainties that was the source of the [Rivet/Contur problems](https://gitlab.com/hepcedar/rivet/-/issues/69).  I suggest adding an `elif` condition like the following:
```python
            if nonzero_uncs[i]:
                [...]
            elif self.uncertainties:
                print("Warning: omitting 'errors' since all uncertainties are zero for bin {} of variable '{}'.".format(i, self.name))
                print("Note that bins with zero content should preferably be omitted completely from the HEPData table.")
```

2021-05-06 11:03 UTC, GraemeWatt commented
@AndreasAlbert, just to mention this issue was raised today by an ATLAS uploader, so it would be good to soon have the PR merged after addressing my comments.

2021-05-06 11:37 UTC, AndreasAlbert commented on hepdata_lib/__init__.py
> +                        })
Change implemented as proposed

2021-05-06 11:37 UTC, AndreasAlbert commented on hepdata_lib/__init__.py
> +            # if at least one of the uncertanities is not zero.
Change implemented as proposed

2021-05-06 11:37 UTC, AndreasAlbert commented on hepdata_lib/helpers.py
> +            nonzero = nonzero | np.any((np.array(unc.values) > 0),axis=1)
Change implemented as proposed

2021-05-06 11:38 UTC, AndreasAlbert commented
@GraemeWatt thanks for reminding me. I implemented your proposals.

2021-05-06 11:51 UTC, AndreasAlbert commented
It's slightly annoying that pylint requirements keep changing under our feet. We should consider fixing pylint to a given version to avoid this (would however require us to periodically upgrade the version and clean up the code according to new requirements then).

2021-05-06 12:00 UTC, AndreasAlbert commented
@GraemeWatt ok, good to merge now if you are happy with the changes

2021-05-06 12:04 UTC, merged