ci: Use micromamba to test Python and ROOT
HEPData/hepdata_lib pull request #220
Opened 2023-02-22 07:25 UTC by matthewfeickert

Resolves #200.

Requires #218 to go in first.

* Use the mamba-org/provision-with-micromamba GitHub action to setup a micromamba enviroment with a ROOT version and CPython version defined by the CI matrix.
   - Set a default shell of a Bash login to automatically source the micromamba environment.
* Test ROOT v6.24.00 and v6.26.10 and all compatible Python versions with them.
   - Exclude versions of Python that are not compatible with ROOT releases.
   - Test on macOS with the latest ROOT release on conda-forge (v6.26.10) and the latest supported CPython version (3.10).
* Install ImageMagick and Ghostscript through conda-forge.
* Remove commented out macOS and Python 2.7 workflows.

2023-02-22 07:26 UTC, matthewfeickert commented on .github/workflows/tests.yml
> +            python-version: "3.10"
ROOT `v6.24.00` isn't compatible with modern Python.

2023-02-22 07:27 UTC, matthewfeickert commented on .github/workflows/tests.yml
> +            python-version: "3.7"
The conda-forge distribution of ROOT `v6.26` isn't compatible with Pythons that are EOL or on the verge of EOL.

2023-02-22 16:08 UTC, matthewfeickert commented
@clelange once PR #218 is merged I can rebase this and then it will be ready to go.

2023-02-22 16:19 UTC, matthewfeickert commented
@clelange thanks for the fast review and merge of PR #218! This is now ready for review. :+1:

2023-02-22 16:28 UTC, clelange requested changes
Thanks once more, this helps a lot! I left a couple of comments in the code. I hope the tests will answer some of my questions 😄

2023-02-22 16:28 UTC, clelange commented on .github/workflows/tests.yml
> +        root-version: ["6.24.00", "6.26.10"]
Any reason not to go with the latest release of 6.24, i.e. 6.24.08?

2023-02-22 16:28 UTC, clelange commented on .github/workflows/tests.yml
> +      uses: mamba-org/provision-with-micromamba@v15
I guess this will get version updates from dependabot if needed?

2023-02-22 16:28 UTC, clelange commented on .github/workflows/tests.yml
> -        cat /etc/ImageMagick*/policy.xml
The tests will hopefully tell if this is still needed or not 😄

2023-02-22 16:28 UTC, clelange commented on .github/workflows/tests.yml
> -#         jupyter nbconvert --ExecutePreprocessor.timeout=600 --ExecutePreprocessor.kernel_name=python2 --ExecutePreprocessor.allow_errors=True --to html --execute examples/*.ipynb
Any particular reason to drop the `nbconvert` tests? I found them quite useful. Would of course need an update to a python3 kernel

2023-02-22 16:28 UTC, clelange commented on .github/workflows/tests.yml
> -#           python3 setup.py test
I would also like to continue having the notebooks tested using `papermill`. What do you think?

2023-02-22 16:35 UTC, matthewfeickert commented on .github/workflows/tests.yml
> +        root-version: ["6.24.00", "6.26.10"]
Nope. That's fine to update to, I was just leaving this as it currently exists.

Instead of using `==` for ROOT I can also just use `=` and specifying down to the minor version (which with conda is the same as `~= x.y.0`) though ROOT doesn't really follow SemVer and so there is no reason to trust that testing against the latest patch release won't break something for an unclear reason. But maybe that's better to catch anyway as it is better to know in CI that things are broken than finding out later.

2023-02-22 16:35 UTC, matthewfeickert commented on .github/workflows/tests.yml
> +      uses: mamba-org/provision-with-micromamba@v15
Yup! This should get rolling updates just like the other GitHub Actions.

2023-02-22 16:36 UTC, matthewfeickert commented on .github/workflows/tests.yml
> -        cat /etc/ImageMagick*/policy.xml
Yeah, I removed this only after I checked that installing from `conda-forge` didn't need this anymore.

2023-02-22 16:40 UTC, matthewfeickert commented on .github/workflows/tests.yml
> -#         jupyter nbconvert --ExecutePreprocessor.timeout=600 --ExecutePreprocessor.kernel_name=python2 --ExecutePreprocessor.allow_errors=True --to html --execute examples/*.ipynb
These still exist and are run against all configurations. This is just remvoing the commented out old macOS jobs that are now folded into the platform matrix above.

2023-02-22 16:52 UTC, matthewfeickert commented on .github/workflows/tests.yml
> -#           python3 setup.py test
```
python -m pytest tests
```

is still getting these in the testing matrix.

2023-02-22 16:58 UTC, matthewfeickert commented on .github/workflows/tests.yml
> +          root=${{ matrix.root-version }}
Using `6.24` and `6.26` along with `root=` instead of `root==` means that this is asking `conda-forge` for something equivalent to `~=6.26.0` in `pip`, for `6.26` for example.

2023-02-22 16:59 UTC, matthewfeickert commented on .github/workflows/tests.yml
> +            python-version: "3.10"
This adds back in macOS tests but just for the latest release, as `macos-latest` is much slower given the limited number of runners and high demands that GitHub has.

2023-02-22 17:05 UTC, matthewfeickert commented on .github/workflows/tests.yml
> -#           python3 setup.py test
From the CI logs:

```
...
python -m pytest tests
============================= test session starts ==============================
platform linux -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/runner/work/hepdata_lib/hepdata_lib, configfile: pyproject.toml
plugins: anyio-3.6.2, pylint-0.19.0, cov-4.0.0
collected 58 items

tests/test_cfilereader.py .......                                        [ 12%]
tests/test_execute_command.py .                                          [ 13%]
tests/test_helpers.py ....                                               [ 20%]
tests/test_notebooks.py .....                                            [ 29%]
tests/test_output.py .                                                   [ 31%]
tests/test_rootfilereader.py ..................                          [ 62%]
tests/test_submission.py ......                                          [ 72%]
tests/test_table.py ........                                             [ 86%]
tests/test_uncertainty.py ...                                            [ 91%]
tests/test_variable.py .....                                             [100%]

=============================== warnings summary ===============================
...
```

2023-02-23 07:36 UTC, clelange commented on .github/workflows/tests.yml
> -#           python3 setup.py test
Right, the issues with the diff view...

2023-02-23 07:51 UTC, clelange commented on .github/workflows/tests.yml
> +          root=${{ matrix.root-version }}
That sounds good! Would you mind changing to `=`?

2023-02-23 07:54 UTC, matthewfeickert commented on .github/workflows/tests.yml
> +          root=${{ matrix.root-version }}
It already does use `=`.

2023-02-23 07:59 UTC, clelange approved these changes
Thanks again! I'll merge this and will then make a new release so that python 2 can then be deprecated.

2023-02-23 07:59 UTC, clelange commented on .github/workflows/tests.yml
> +          root=${{ matrix.root-version }}
Sorry, I see it now, was looking at an outdated diff for some reason...

2023-02-23 08:00 UTC, merged

2023-02-23 08:05 UTC, matthewfeickert commented
> Thanks again! I'll merge this and will then make a new release so that python 2 can then be deprecated.

If you want to make a release before removing Python 2 support then let me make a PR that adds a `python_requires` _before_ you make the release so that this release gets that. I would also recommend making a _minor_ release _after_ PR #221 to signify that a Python version has been dropped.