Related records
HEPData/hepdata_lib pull request #232
Opened 2023-08-23 13:47 UTC by ItIsJordan

This pull request provides support for the new bidirectional linking features of HEPData [(docs)](https://hepdata-submission.readthedocs.io/en/latest/bidirectional.html). Adds support for the new related data fields.

2023-08-24 07:39 UTC, clelange commented
Thanks for this! Is there a real need to deprecate support for python 3.6? I know it's end-of-life, but there are still lots of systems around that have this as default version.

2023-08-24 09:40 UTC, GraemeWatt commented
> Thanks for this! Is there a real need to deprecate support for python 3.6? I know it's end-of-life, but there are still lots of systems around that have this as default version.

I was planning to ask you about this, @clelange.  The issue I had was that the CI (using GitHub Actions) for the `hepdata-validator` started failing for Python 3.6 using the `ubuntu-latest` image (see actions/setup-python/issues/561).  I thought it was simplest just to drop Python 3.6 support given that security support ended on 23 Dec 2021 (https://endoflife.date/python).  If you really need `hepdata_lib` to be compatible with Python 3.6, I can look into reinstating support for the `hepdata-validator` (for example, by testing with an older Ubuntu image) and release a new version of the `hepdata-validator`, but I'm reluctant to do this unless it's really needed.  At some point, people need to move to newer Python versions.  Let me know what you think.

By the way, @ItIsJordan still needs to fix a problem with the linting that causes tests to fail, so I moved the PR to "Draft" status for now.

2023-08-24 12:34 UTC, GraemeWatt commented
> Thanks for this! Is there a real need to deprecate support for python 3.6? I know it's end-of-life, but there are still lots of systems around that have this as default version.

On reflection, I agree that we don't need to drop Python 3.6 support unnecessarily.  I've just merged HEPData/hepdata-validator#54 that uses the older `ubuntu-20.04` image to run Python 3.6 tests (and I've added tests for Python 3.10 and 3.11).  I've released a new version [hepdata-validator 0.3.5](https://pypi.org/project/hepdata-validator/0.3.5/) that supports Python 3.6.

@ItIsJordan, can you please upgrade the `hepdata-validator` version and revert 009478b4c048a58ab447b90982a0d16c9ce03a62?  You can see if the Python 3.6 tests run with `ubuntu-latest`, otherwise you might need to modify the `hepdata_lib` workflows to use `ubuntu-20.04` as I did in HEPData/hepdata-validator#54.

2023-08-24 14:52 UTC, ItIsJordan commented
I have made those changes now.

2023-08-24 15:12 UTC, clelange reviewed
Thanks, I've left one suggestion and one comment. Could you please have a look?

2023-08-24 15:12 UTC, clelange commented on hepdata_lib/__init__.py
> +        # Check against regex here too, maybe?
Not sure I understand this comment, isn't this what you're doing?

2023-08-24 15:39 UTC, GraemeWatt requested changes

2023-08-24 15:39 UTC, GraemeWatt commented on docs/usage.rst
> +In this example, we are adding a link to the table with a DOI of: `"10.17182/hepdata.1.v2/t3"`.
This example DOI doesn't actually exist.  If we change it to a link, better to use a valid one from [hepdata.net](https://www.hepdata.net).  By the way, @ItIsJordan, note that `.rst` files use ``` ``code`` ``` (two backticks) rather than `` `code` `` (one backtick) in `.md` files.

2023-08-24 15:47 UTC, ItIsJordan commented on hepdata_lib/__init__.py
> +        # Check against regex here too, maybe?
Sorry, I forgot to remove that comment, it was before the check was added. I will update this,

2023-08-24 16:22 UTC, ItIsJordan commented on docs/usage.rst
> +In this example, we are adding a link to the table with a DOI of: `"10.17182/hepdata.1.v2/t3"`.
Thank you for this!

2023-08-25 00:02 UTC, GraemeWatt approved these changes
Looks good to me.  @clelange : if you're happy with the changes, could you please merge this PR and make a new release of `hepdata_lib`?  Jordan will [talk](https://conference.ippp.dur.ac.uk/event/1178/contributions/6467/) about the new HEPData functionality at the [IPPP workshop](https://conference.ippp.dur.ac.uk/event/1178/) next Wednesday.  It would be good if data submitters could shortly start to add bidirectional links to their submissions via `hepdata_lib`.

2023-08-25 11:10 UTC, clelange commented on docs/usage.rst
> +The documentation for this feature can be found here: (`Linking Tables`_).
```suggestion
The documentation for this feature can be found here: `Linking Tables`_.
```

2023-08-25 11:11 UTC, clelange commented on docs/usage.rst
> +The documentation for this feature can be found here: (`Linking Tables`_).
Suggest to remove parentheses here.

2023-08-25 11:13 UTC, clelange commented
I made one small change, now just waiting for the tests to pass, then I will merge and create a new release this afternoon.

2023-08-25 12:20 UTC, merged