Add support for inhomogenous error breakdowns
HEPData/hepdata_lib pull request #265
Opened 2024-07-22 13:16 UTC by 20DM

Proposal solution for the feature discussed in #229 :

The HepData validator already allows for cases where different bins have different error breakdowns, but `hepdata_lib` currently does not support this.

With this change set one can suppress individual sources by setting them to `None`.

2024-07-22 14:34 UTC, GraemeWatt requested changes
Thanks for the PR!  Can you please add a test in `tests/test_uncertainty.py` to cover the new feature and add some explanation under [Uncertainties](https://github.com/HEPData/hepdata_lib/blob/main/docs/usage.rst#uncertainties)? in the documentation?

2024-07-22 23:40 UTC, GraemeWatt commented
Thanks for adding the test and expanding the docs.  The CI is failing due to issues with `pylint`.  Can you please modify the code so that the `pylint` checks pass?  See [Analysing the code](https://hepdata-lib.readthedocs.io/en/latest/dev.html#analysing-the-code) in the developer docs.

2024-07-23 06:44 UTC, 20DM commented on hepdata_lib/helpers.py
> +        return value
Ouff, I will take a look!

I just wanted to highlight this part of the change set, which I had to put in to make the unit test pass, but it may not be what we want in general (i.e. for non-Uncertainty-type classes)? I didn't see this in my local tests at first, because the sanitising function isn't called when appending to the values array as part of a loop.

2024-07-23 11:25 UTC, GraemeWatt requested changes
Thanks for fixing the linting for the tests.  However, the CI still gives a message:
```
************* Module hepdata_lib
hepdata_lib/__init__.py:237:4: R0912: Too many branches (13/12) (too-many-branches)

-----------------------------------
Your code has been rated at 9.99/10
```
Could you please fix this too?  If you don't see an easy way to refactor the `make_dict` function to avoid this warning, it can be suppressed by adding a line `# pylint: disable=too-many-branches` at the top of the function, but this should be avoided if possible.  I think it's a current bug in the CI that the "Run pylint" still passes, so I've opened a separate PR #267 to address it.

2024-07-23 11:25 UTC, GraemeWatt commented on hepdata_lib/helpers.py
> +        return value
I think that's fine and it shouldn't have unintended consequences, since previously `sanitize_value(None)` would have just given an exception from `float(None)`.  The docstring of `sanitize_value` should be modified, however, to mention that a `value` of `None` is now allowed.

2024-07-23 13:30 UTC, 20DM commented
> Thanks for fixing the linting for the tests. However, the CI still gives a message:
> 
> ```
> ************* Module hepdata_lib
> hepdata_lib/__init__.py:237:4: R0912: Too many branches (13/12) (too-many-branches)
> 
> -----------------------------------
> Your code has been rated at 9.99/10
> ```
> 
> Could you please fix this too? If you don't see an easy way to refactor the `make_dict` function to avoid this warning, it can be suppressed by adding a line `# pylint: disable=too-many-branches` at the top of the function, but this should be avoided if possible. I think it's a current bug in the CI that the "Run pylint" still passes, so I've opened a separate PR #267 to address it.

Urgh - well, this can be circumvented by moving the additional if statement into a separate list comprehensions, e.g. like so
```
for unc in [ unc for unc in self.uncertainties if not unc.values[i] is None ]:
    ...
```
but that adds an extra loop for no good reason. So my preference would be to silence the linter here, but I'd leave that call to you. 🤷

2024-07-23 13:36 UTC, 20DM commented on hepdata_lib/helpers.py
> +        return value
Thanks - done now!

2024-07-23 15:13 UTC, GraemeWatt approved these changes
I've added `# pylint: disable=too-many-branches` at the top of the `make_dict` function, added `NoneType` in the docstring of the `sanitize_value` function, and merged the last commit to the `main` branch.  The [workflow run](https://github.com/HEPData/hepdata_lib/actions/runs/10060011699) for the separate "Run pylint on hepdata_lib" step now fails before adding the `# pylint: disable=too-many-branches` line, as expected.  I'll let @clelange perform the final review and merge.

2024-07-25 08:24 UTC, clelange approved these changes
Thanks for the contribution @20DM and for the review @GraemeWatt !

2024-07-25 08:25 UTC, merged